version: 2.1

jobs:
  unit-test: # this can be any name you choose
    docker:
      - image: node:18.16.0
    steps:
      - checkout
      - run:
          name: Install pnpm package manager
          command:
            npm i -g pnpm@7.24.3
      - run:
          name: Install Dependencies
          command:
            pnpm install
      - run:
          name: Unit test
          command: yarn test


#  build:
#    docker:
#      - image: cimg/node:16.17.0
#    steps:
#      - checkout
#      - setup_remote_docker:
#          version: 20.10.14
#          docker_layer_caching: true
#
#      - run:
#          name: Update known hosts
#          command: ssh-keyscan -H $SERVERNAME >> ~/.ssh/known_hosts
#      - run:
#          name: Docker Build
#          command: docker build -t 874470891/self-study-web .
#      - run:
#          name: Docker Login
#          command: |
#            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
#            docker push 874470891/self-study-web
#      - run:
#          name: Deploy
#          command: ssh jingsong@$SERVERNAME "cd ./app/self-study-web/ && sh ./bin/deploy.sh"

#      - run:!
#          name: Docker Start
#          command: docker run --name app --network=host -p 3000:3000 -d aslanxiong/node-web-app

workflows:
  version: 2
  test_and_build:
    jobs:
      - unit-test

